**NumPy** is the fundamental package for scientific computing with Python. It contains among other things:
<ul>
    <li>a powerful N-dimensional array object</li>
    <li>methods for processing array</li>
    <li>element by element array oprations</li>
    <li>useful linear algebra, Fourier transform, and random number capabilities</li>
    <li>sophisticated (broadcasting) functions</li>
    <li>tools for integrating C/C++ and Fortran code</li>
</ul>

**Note:** NumPy Array is also called as Ndarray and numpy.array != array.array (Python Library class)

In [4]:
# import numpy module
import numpy as np

**numpy.arange** return evenly spaced values within a given interval like range() builtin function

In [7]:
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


**numpy.reshape** gives a new shape to an array without changing its data

In [8]:
a = a.reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


**numpy.shape** return the shape of an array

In [9]:
a.shape

(3, 5)

**numpy.ndim** return the number of dimensions of an array

In [10]:
a.ndim

2

**numpy.dtype** create a data type object
**numpy.dtypename** returns a bit-width name for this data-type

In [11]:
a.dtype.name

'int32'

In [13]:
b = np.arange(5, dtype=float)
'Array', b, 'Type', b.dtype.name

('Array', array([0., 1., 2., 3., 4.]), 'Type', 'float64')

**numpy.itemsize** return the size in bytes of each element of the array

In [14]:
a.itemsize

4

In [15]:
type(a)

numpy.ndarray

**numpy.size** return the number of elements along a given axis

In [16]:
a.size

15

**numpy.nbytes** returns total bytes consumed by the elements of the array

In [20]:
a.nbytes

60

In [21]:
# Also gives total bytes consumed by the elements of the array
a.itemsize * a.size

60

**numpy.prod** return the product of array elements over a given axis

In [23]:
np.prod(a)

0

**Creating array**

In [17]:
np.array([2,3,4])

array([2, 3, 4])

In [18]:
lis = [1,2,3,4,5,8]
np.array(lis)

array([1, 2, 3, 4, 5, 8])

In [24]:
np.array([1.2, 3.5, 5.1])

array([1.2, 3.5, 5.1])

In [19]:
# 2D array
np.array([(1,2,3), (5,8,7)])

array([[1, 2, 3],
       [5, 8, 7]])

In [25]:
np.array([[1,2,3], [5,8,7]])

array([[1, 2, 3],
       [5, 8, 7]])

In [27]:
np.array([(1,2,3), [5,8,7]])

array([[1, 2, 3],
       [5, 8, 7]])

In [26]:
np.array( [ (1,2), (3,4) ], dtype=complex )

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

**numpy.zeros** return a new array of given shape and type, filled with zeros

In [29]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
np.zeros((3,2), dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [33]:
np.zeros((3,2,4), dtype=np.int16)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

**numpy.zeros_like** return an array of zeros with the same shape and type as a given array

In [49]:
s = np.array([[1,2,3], [5,8,7]])
np.zeros_like(s)

array([[0, 0, 0],
       [0, 0, 0]])

**numpy.ones** return a new array of given shape and type, filled with ones

In [34]:
np.ones( (2,3,4), dtype=np.int16 ) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

**numpy.ones_like** return an array of ones with shape and type of input.

In [50]:
s = np.array([[1,2,3], [5,8,7]])
np.ones_like(s)

array([[1, 1, 1],
       [1, 1, 1]])

**numpy.empty** return a new array of given shape and type, without initializing entries

In [40]:
np.empty([2, 2])

array([[0., 0.],
       [0., 0.]])

In [55]:
np.empty([2, 2], dtype=int)

array([[1461828352,        583],
       [         0,          0]])

**numpy.empty_like** return an empty array with shape and type of input

In [57]:
d = np.array([[1,2,3], [5,8,7]])
np.empty_like(d)

array([[1461828352,        583,          0],
       [         0,          1,          0]])

**numpy.full** return a new array of given shape and type, filled with `fill_value`

In [44]:
np.full((2, 2), np.inf)

array([[inf, inf],
       [inf, inf]])

In [46]:
np.full((2, 2), None)

array([[None, None],
       [None, None]], dtype=object)

**numpy.full_like** return a full array with the same shape and type as a given array

In [66]:
g = np.array([[1,2,3], [5,8,7]], dtype=np.double)
np.full_like(g, np.nan)

array([[nan, nan, nan],
       [nan, nan, nan]])

In [63]:
f = np.array([[1,2,3], [5,8,7]])
np.full_like(f, np.nan, dtype=np.double)

array([[nan, nan, nan],
       [nan, nan, nan]])

**numpy.linspace** return evenly spaced numbers over a specified interval

In [47]:
np.linspace( 0, 2, 9 ) 

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

**numpy.identity** return the identity array

In [67]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
np.identity(3, dtype=np.int16)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

**Operations**

In [132]:
a = np.array([20,30,40,50])
b = np.arange(4)
a, b

(array([20, 30, 40, 50]), array([0, 1, 2, 3]))

In [133]:
# Elementwise addition
a + b

array([20, 31, 42, 53])

In [134]:
# Elementwise subtraction
a - b

array([20, 29, 38, 47])

In [135]:
# Elementwise division
a / b

C:\Users\anilk\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([        inf, 30.        , 20.        , 16.66666667])

In [105]:
# Square
a**2

array([ 400,  900, 1600, 2500], dtype=int32)

In [106]:
# Qube
b**3

array([ 0,  1,  8, 27], dtype=int32)

In [107]:
a>30

array([False, False,  True,  True])

In [112]:
# Squre root
np.sqrt(a**2)

array([20., 30., 40., 50.])

In [108]:
10*np.sin(b)

array([0.        , 8.41470985, 9.09297427, 1.41120008])

In [72]:
# Elementwise product
a * b

In [74]:
# Matrix product
a @ b

260

In [75]:
# Another matrix product
a.dot(b)

260

**Some operations, such as += and *=, act in place to modify an existing array rather than create a new one**

In [76]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a, b

(array([[1, 1, 1],
        [1, 1, 1]]), array([[0.80623452, 0.56368881, 0.14251216],
        [0.36229748, 0.49148757, 0.14150078]]))

In [77]:
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [78]:
b += a
b

array([[3.80623452, 3.56368881, 3.14251216],
       [3.36229748, 3.49148757, 3.14150078]])

In [80]:
a += b                  # b is not automatically converted to integer type

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [86]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
# Sum of all elements
a.sum()

66

In [88]:
# Sum of elements in each column
a.sum(axis=0)

array([12, 15, 18, 21])

In [89]:
# Sum of elements in each row
a.sum(axis=1)

array([ 6, 22, 38])

In [94]:
# cumulative sum of each element
a.cumsum() 

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66], dtype=int32)

In [92]:
# cumulative sum along each column
a.cumsum(axis=0) 

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

In [93]:
# cumulative sum along each row
a.cumsum(axis=1) 

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [95]:
# Min of array
a.min()

0

In [96]:
# Min of each column
a.min(axis=0)

array([0, 1, 2, 3])

In [97]:
# Min of each row
a.min(axis=1)

array([0, 4, 8])

In [98]:
# Max of array
a.max()

11

In [99]:
# Max of each column
a.max(axis=0)

array([ 8,  9, 10, 11])

In [100]:
# Max of each row
a.max(axis=1)

array([ 3,  7, 11])

## Indexing, Slicing and Iterating

## One-dimensional

In [113]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [114]:
# Get a specific element
a[2]

8

In [116]:
# Get specific part of array
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [120]:
# Update specific element
a[:6:2] = -1000 # or a[0:6:2] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [121]:
# Reverse an array
a[::-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [123]:
for el in a:
    print(el) # Do something(operation) as required

-1000
1
-1000
27
-1000
125
216
343
512
729


## Multidimensional

**numpy.fromfunction** construct an array by executing a function over each coordinate

In [124]:
def func(x,y):
    return 10*x+y

d = np.fromfunction(func,(4,5), dtype=int)
d

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [126]:
# Get a specific element [r, c]
d[2,3]

23

In [127]:
# Get a specific row 
d[0, :]

array([0, 1, 2, 3, 4])

In [128]:
# Get a specific column
d[:, 2]

array([ 2, 12, 22, 32])

In [129]:
# Getting a little more fancy [startindex:endindex:stepsize]
d[0, 1:-1:2] # or d[0, 1::2]

array([1, 3])

In [136]:
# Get the last row
d[-1] # or d[-1,:]

array([30, 31, 32, 33, 34])

In [138]:
# Get each column in the second and third row of d
d[1:3, :] # or d[1:3]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [139]:
# Get specific part of an array
d[1:3, 2:4]

array([[12, 13],
       [22, 23]])